name: TechTrends - Package with Docker
on:
  push:
   branches:
     - main

jobs:
  build:
   runs-on: ubuntu-latest
   timeout-minutes: 10
   steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
      with:
       python-version: '3.8' 
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set Version Variable
      run: |
          VER=$(cat VERSION)
          echo "VERSION=$VER" >> $GITHUB_ENV
      working-directory: project/techtrends
    - name: build docker image
      run: docker build -t techtrends:${{ env.VERSION }} .
      working-directory: project/techtrends
    - name: tag docker image
      run: docker tag techtrends:${{ env.VERSION }} mmsaad85/techtrends:${{ env.VERSION }}
      working-directory: project/techtrends
    - name: push to docker hub
      run: docker push mmsaad85/techtrends:${{ env.VERSION }}
      working-directory: project/techtrends